### ISSUE TITLE
Add texlive module

### ISSUE THREAD

**Issue by wolfv** [flathub/shared-modules#16] opened 2018-05-06 08:12 UTC
I am wondering if there is any interest in adding a texlive module here? 

We've created a working flatpak installation for TexLive 2018 for UberWriter (https://github.com/UberWriter/uberwriter/issues/46)

We think TexLive could be something that makes sense to be shared amongst other apps that want to use LaTeX (also, it's a rather big package).

**Comment by barthalion** [comment] 2018-05-06 16:07
I wonder if it wouldn't be better to have it as runtime extension. @TingPing @nedrichards your thoughts?

**Comment by wolfv** [comment] 2018-05-07 07:13
@somas95 do you remember how long it took?

@TingPing we currently do not "build" TexLive but rather use their command-line installer to download the packages from their distribution. Not sure if that's still fine for inclusion here. It's immensely useful though, if you want to use LaTeX.

There is at least gnome-latex (@swilmet et al) who could probably make use of it. And @Alexander-Wilms also expressed interest.

**Comment by wolfv** [comment] 2018-05-07 07:29
Out of curiosity, does making it a runtime extension have any impact on e.g. app startup time?

**Comment by somas95** [comment] 2018-05-07 09:54
About build time, it's not too long, it depends mostly on the internet conexion as is more an installer than a makefile. It retrieves the packages from the texlive repositories. For me its ~2 min. The thing is we only install a small subset of all the TexLive packages (they're thousands), and every user case may be interested on a different subset of those packages
If an extension could be mounted by different applications maybe the most space efficient way would be to have an extension for every TexLive collection (collections are groups of packages, there are like 10-12 collections)

**Comment by Alexander-Wilms** [comment] 2018-05-07 15:44
I think `"build-args" : ["--share=network"]` is not allowed on Flathub. Maybe there's a way to use the iso instead.

**Comment by TingPing** [comment] 2018-05-07 17:19
Right, you can't just download things, you have to build them.

**Comment by wolfv** [comment] 2018-05-07 17:44
Just out of curiosity, what's the reasoning behind that? For me the importance of the sandbox lies during execution on the users computer. 

But anyhow, I think we'll try going with the ISO for this case, then.

**Comment by somas95** [comment] 2018-05-07 17:48
Or maybe do a package from our install. The iso could be very big

**Comment by barthalion** [comment] 2018-05-07 18:06
Disabled network access gives us basic reproducibility.

**Comment by RoyiAvital** [comment] 2018-07-30 14:51
Shared packages of TeXLive and **MiKTeX** will be great!
Just need to take care of the case the TeX Distribution needs to download new package, where should it be installed?

Many students needs those and FlatPak makes life much easier than other ways to install on Linux.  
I'd really want to see MiKTeX and not only TeXLive.

**Comment by jakobjakobson18** [comment] 2019-03-09 11:21
As the extension [org.freedesktop.Sdk.Extension.texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive) was created, this issue can be closed.

**Comment by RoyiAvital** [comment] 2019-03-09 15:37
@jakobjakobson18 , Any chance to have one for MiKTeX as well (@MiKTeX)?

**Comment by jakobjakobson18** [comment] 2019-03-10 19:38
As far as I understand [LaTeX Pojekt](https://www.latex-project.org/get/) recommends TeX Live as the latex distribution for unix/Linux. Also there would not be any advantage having two linux distributions that provide the same functionality.

And if you are missing the auto-installation feature of miktex, this should not be an issue as the current latex extension provides plenty of packages.

**Comment by RoyiAvital** [comment] 2019-03-11 05:47
I think diversity and options are good, not bad.
Hence I think an option o have MiKTeX will be great.

**Comment by jakobjakobson18** [comment] 2019-03-11 21:12
Well I guess then it's up to you to either build such a package yourself or convince someone that it important enough to build another tex extension.

**Comment by lumingzh** [comment] 2021-09-24 05:03
@jakobjakobson13  Hi, can you tell me what is the situation of [org.freedesktop.Sdk.Extension.texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive)?

I installed Setzer from flathub, it depends on this sdk extension, but the installed size of setzer itself is 6.7GB. So I assume the huge size is texlive, but it's not installed as normal runtime extension and not listed in installed apps/runtimes.

So it can not be used by other latex editors as shared module or shared runtime, and every latex editor must bundle its copy of this sdk extension, am I right? Thank you.

**Comment by hfiguiere** [comment] 2021-09-24 12:59
There are two ways to use the texlive extension: at build time, copy stuff, or have it install and use it in place at runtime. Setzer could switch to the latter I think.

Note that the way ostree works mean that the disk space is actually shared anyway, so the impact might not be significant.

**Comment by bbhtt** [comment] 2024-02-14 11:37
Closing since texlive extension exists for a long time. It doesn't make sense for something as big as texlive to be rebuilt and reinstalled repeatedly.

**Closed by bbhtt** 2024-02-14 11:37 UTC
