### ISSUE TITLE
Add SDL_sound module

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/shared-modules#41] opened 2019-01-02 22:25 UTC
Please, consider adding SDL_sound module. It is required, for example, by [compressed audio](https://www.dosbox.com/wiki/Building_DOSBox_with_MinGW#Adding_support_for_compressed_audio_on_diskimages_.28Optional.29) feature of DOSBox.

**Comment by AsciiWolf** [comment] 2019-01-02 22:32
Yeah, I'll try to make a PR when I have some time. Unfortunately, I am quite busy lately. :-(

**Comment by bam80** [comment] 2019-01-02 22:41
Maybe we should start with adding SDL2, what do you think @AsciiWolf ?

**Comment by AsciiWolf** [comment] 2019-01-02 22:46
@bam80 I don't think that the stable DOSBox release supports SDL2. And there are more projects on Flathub that still use SDL1.

**Comment by TingPing** [comment] 2019-01-02 23:13
SDL2 is in the runtime...

**Comment by bam80** [comment] 2019-01-04 00:40
SDL_sound code is managed by Mercurial, which is unsupported by Flatpak.
[The latest officially released binaries and source](http://icculus.org/SDL_sound/downloads/) doesn't contain latest release.

Any advise how to deal with the source?

**Comment by jurf** [comment] 2019-01-04 10:20
According to the [Mercurial web interace](https://hg.icculus.org/icculus/SDL_sound/tags), the newest release is 1.0.3, which _is_ available there: https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz

**Comment by bam80** [comment] 2019-01-04 22:47
@jurf no, it's too old.
Hope http://hg.icculus.org/icculus/SDL_sound/archive/final-lgpl-revision.tar.bz2 give us stable content..

**Comment by TingPing** [comment] 2019-01-04 22:53
> @jurf no, it's too old.
> Hope http://hg.icculus.org/icculus/SDL_sound/archive/final-lgpl-revision.tar.bz2 give us stable content..

It just looks like he never made a release. That tag is clearly just before a re-license not a release.

Honestly probably something to discuss with the maintainer himself as he is pretty responsive.

@AsciiWolf 	In the short term maybe just bundle it if nothing else is using it.

**Comment by bam80** [comment] 2019-01-04 22:58
If so, let's ask @rcgordon himself.
I already send an email to him, but got no response so far. So I just going to use the link above if nothing changes..

**Comment by rcgordon** [comment] 2019-01-05 01:50
Doing an official release because FlatPak doesn't support Mercurial is not a good reason to do an official release.

SDL_sound 2 (what the default branch will eventually become) isn't ready, and the stable-1.0 branch is a total mess that needs a lot of work to be release-ready.

So this is a stupid question: how hard would it be to add Mercurial support to FlakPak? I could be interested in patching that in if that solves this specific problem at the same time.

**Comment by TingPing** [comment] 2019-01-05 14:09
> Doing an official release because FlatPak doesn't support Mercurial is not a good reason to do an official release.

That isn't the reason, the reason is Flathub targets stable releases. Taking a random snapshot from the repo is not ideal.

**Comment by TingPing** [comment] 2019-01-05 14:11
> So this is a stupid question: how hard would it be to add Mercurial support to FlakPak? I could be interested in patching that in if that solves this specific problem at the same time.

It would be something like this: https://github.com/flatpak/flatpak-builder/commit/4510aa2359f44dffe0bb42c21e13a8d4f77e3f50

Might look like a bit but its mostly boilerplate.

**Comment by rcgordon** [comment] 2019-01-06 01:53
> That isn't the reason

(Sorry, someone emailed me about this shortly after this issue was opened and said "for Flatpak's build of SDL_sound I would like to checkout stable-1.0 branch. The problem is, Flatpak doesn't support Mercurial (yet?)." ... I assumed it was in relation to this!)

**Comment by barthalion** [comment] 2019-01-06 20:19
Is there anything actually broken in the latest release? Not saying Mercurial support wouldn't be useful, I'm just a little bit out of the loop about the reason behind this issue.

**Comment by bam80** [comment] 2019-01-06 21:59
@barthalion no, it's just about age of the latest release which is a bit scary

**Comment by bam80** [comment] 2019-01-07 13:44
[Failed to download sources: port 443: Connection refused](https://github.com/flatpak/flatpak-builder/issues/250)

**Comment by bam80** [comment] 2019-01-10 13:36
> @AsciiWolf In the short term maybe just bundle it if nothing else is using it.

Agree, and it was bundled with DOSBox in https://github.com/flathub/com.dosbox.DOSBox/pull/13.
So we could close this if no other demand.

**Comment by bbhtt** [comment] 2024-09-29 13:37
Only 3 apps are using sdl_sound at the moment and 1 of those 3 is EOL. 

If there are not enough apps using it, then there isn't a reason to include it in shared-modules. Feel free to reopen if it is used by enough apps

https://github.com/flathub/io.github.sharkwouter.Minigalaxy/blob/0ae42cea2ee93a0a7d69981a92ca521a2a20b08a/addons/dosbox-staging.json#L31

https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Boxtron/blob/173cae5fd38840d6ce5dbe0f0a3ce456bec20a2a/com.valvesoftware.Steam.CompatibilityTool.Boxtron.yml#L48

https://github.com/flathub/com.dosbox.DOSBox/blob/41e553fcfeb4da49c3dcb2973680a993acfb7fde/com.dosbox.DOSBox.json#L36

**Closed by bbhtt** 2024-09-29 13:37 UTC
